-- CAKE PASSWORD GENERATION

-- Write a query to display the cake name and password. Password should be generated by concatenating the first three characters of cake name and the first three characters of cake id and give an alias name as Password. Sort the result based on descending order of Password.
-- (HINT: Retrieve data from Cakes table. Data is Case Sensitive)


SELECT Cake_name, 
CONCAT(SUBSTR(Cake_name,1,3), SUBSTR(Cake_id,1,3)) AS Password
FROM Cakes
ORDER BY Password DESC;